-- MySQL Script generated by MySQL Workbench
-- Tue Nov 15 12:42:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(15) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `reference` VARCHAR(100) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `location_user_idx` (`id_user` ASC),
  CONSTRAINT `location_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(225) NOT NULL,
  `stars` DECIMAL(2,1) NULL,
  `reviews` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productImages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(150) NOT NULL,
  `norden` INT NOT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `productImages_products_idx` (`id_product` ASC),
  CONSTRAINT `productImages_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pricesForQuantity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pricesForQuantity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(6,2) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pricesForQuantity_products_idx` (`id_product` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `pricesForQuantity_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_fav_or_cart` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_pricesForQuantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `users_favorites_idx` (`id_user` ASC),
  INDEX `pricesForQuantity_favorites_idx` (`id_pricesForQuantity` ASC),
  CONSTRAINT `users_favorites`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pricesForQuantity_favorites`
    FOREIGN KEY (`id_pricesForQuantity`)
    REFERENCES `mydb`.`pricesForQuantity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paidProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paidProducts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `imgUrl` VARCHAR(200) NOT NULL,
  `totalPaid` DECIMAL(6,2) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_paidProducts_idx` (`id_user` ASC),
  UNIQUE INDEX `imgUrl_UNIQUE` (`imgUrl` ASC),
  CONSTRAINT `user_paidProducts`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listPaidProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`listPaidProducts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `totalPaid` DECIMAL(7,2) NOT NULL,
  `id_paidProducts` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `paidProducts_boletas_idx` (`id_paidProducts` ASC),
  CONSTRAINT `paidProducts_boletas`
    FOREIGN KEY (`id_paidProducts`)
    REFERENCES `mydb`.`paidProducts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`boletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`boletas` (
  `id` INT NOT NULL,
  `id_listPaidProducts` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `listPaidProducts_boletas_idx` (`id_listPaidProducts` ASC),
  CONSTRAINT `listPaidProducts_boletas`
    FOREIGN KEY (`id_listPaidProducts`)
    REFERENCES `mydb`.`listPaidProducts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
