-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 01:28:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `celnumber` VARCHAR(45) NULL,
  `password` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(15) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `reference` VARCHAR(100) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `location_user_idx` (`id_user` ASC),
  CONSTRAINT `location_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `stars` DECIMAL(2,1) NULL,
  `id_productCategory` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_products_productCategory1_idx` (`id_productCategory` ASC),
  CONSTRAINT `fk_products_productCategory1`
    FOREIGN KEY (`id_productCategory`)
    REFERENCES `mydb`.`productCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productImages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(150) NOT NULL,
  `norden` INT NOT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `productImages_products_idx` (`id_product` ASC),
  CONSTRAINT `productImages_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pricesForQuantity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pricesForQuantity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `subQuantity` VARCHAR(45) NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pricesForQuantity_products_idx` (`id_product` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `pricesForQuantity_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_fav_or_cart` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_pricesForQuantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `users_favorites_idx` (`id_user` ASC),
  INDEX `pricesForQuantity_favorites_idx` (`id_pricesForQuantity` ASC),
  CONSTRAINT `users_favorites`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pricesForQuantity_favorites`
    FOREIGN KEY (`id_pricesForQuantity`)
    REFERENCES `mydb`.`pricesForQuantity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paidProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paidProducts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `imgUrl` VARCHAR(200) NOT NULL,
  `totalPaid` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_paidProducts_idx` (`id_user` ASC),
  UNIQUE INDEX `imgUrl_UNIQUE` (`imgUrl` ASC),
  CONSTRAINT `user_paidProducts`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listPaidProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`listPaidProducts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `totalPaid` INT NOT NULL,
  `id_paidProducts` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `paidProducts_boletas_idx` (`id_paidProducts` ASC),
  CONSTRAINT `paidProducts_boletas`
    FOREIGN KEY (`id_paidProducts`)
    REFERENCES `mydb`.`paidProducts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`boletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`boletas` (
  `id` INT NOT NULL,
  `id_listPaidProducts` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `listPaidProducts_boletas_idx` (`id_listPaidProducts` ASC),
  CONSTRAINT `listPaidProducts_boletas`
    FOREIGN KEY (`id_listPaidProducts`)
    REFERENCES `mydb`.`listPaidProducts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orderStatus` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `timeUpdate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `codTracking` VARCHAR(15) NULL,
  `noteOrder` VARCHAR(225) NULL,
  `id_listPaidProducts` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orderStatus_listPaidProducts1_idx` (`id_listPaidProducts` ASC),
  CONSTRAINT `fk_orderStatus_listPaidProducts1`
    FOREIGN KEY (`id_listPaidProducts`)
    REFERENCES `mydb`.`listPaidProducts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productReview`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productReview` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productReview` VARCHAR(200) NULL,
  `id_user` INT NOT NULL,
  `id_products` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productReview_users1_idx` (`id_user` ASC),
  INDEX `fk_productReview_products1_idx` (`id_products` ASC),
  CONSTRAINT `fk_productReview_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productReview_products1`
    FOREIGN KEY (`id_products`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id_permissions` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_rol` INT NULL,
  PRIMARY KEY (`id_permissions`),
  UNIQUE INDEX `id_permissions_UNIQUE` (`id_permissions` ASC),
  INDEX `rol_permission_idx` (`id_rol` ASC),
  INDEX `user_permission_idx` (`id_user` ASC),
  CONSTRAINT `rol_permission`
    FOREIGN KEY (`id_rol`)
    REFERENCES `mydb`.`rol` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_permission`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`portada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url_tablet` VARCHAR(150) NULL,
  `url_mobile` VARCHAR(150) NULL,
  `url` VARCHAR(150) NULL,
  `description` VARCHAR(45) NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_portada_idx` (`id_user` ASC),
  CONSTRAINT `user_portada`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
